// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace WorkoutTime
{
	public partial class PlayTableViewCell : UITableViewCell, IIntervalTableViewCell
	{
		public PlayTableViewCell (IntPtr handle) : base (handle) { }

		public void SetData (Interval interval)
		{
			intervalTimeLabel.Text = $"{interval.Time} {interval.TimeDetail}";
			intervalTitleLabel.Text = interval.DisplayTitle;
		}
	}
}
