// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace WorkoutTime
{
	public partial class PlayViewController : UIViewController
	{
		public PlayViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
